# Workflow for creating releases

name: Semantic Release

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows the workflow to be reused in other repositories
  workflow_call:
    
permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write
  id-token: write 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  semantic-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: export-npm-token
        run: echo "NPM_TOKEN=" >> $GITHUB_ENV

      - id: create-config
        run: |
          configFile=".releasesrc.json"
          echo '
          {
            "plugins": [
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "conventionalcommits",
                  "releaseRules": [{"type": "chore", "release": "patch"}]
                }
              ],
              [
                "@semantic-release/release-notes-generator",
                [
                  "preset": "conventionalcommits"
                ]
              ],
              "@semantic-release/changelog",
              "@semantic-release/github",
              [
                "@semantic-release/git",
                {
                  "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
                }
              ]
            ]
            "branches": ["master", "main"]
          }          
          ' >> $configFile
          cat $configFile

      - uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: v21.1.1
          branches: |
            ["master", "main"]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/exec
            conventional-changelog-conventionalcommits@6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
