# Workflow for creating releases

name: Semantic Release

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows the workflow to be reused in other repositories
  workflow_call:
    
permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write
  id-token: write 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  semantic-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: create-config
        run: |
          configFile=".releasesrc.json"
          echo '
          {
            "branches": [
              "master", 
              "main"
            ],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github",
              [
                "@semantic-release/exec",
                {
                  "prepareCmd": "set-version ${nextRelease.version}",
                  "publishCmd": "publish-package"
                }
              ]
            ]
          }       
          ' >> $configFile
          cat $configFile

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: '["main", "master"]'
          extra_plugins: |
            "@semantic-release/commit-analyzer"
            "@semantic-release/release-notes-generator"
            "@semantic-release/github"¨
            "@semantic-release/exec"
